### ISSUE TITLE
cmake error while building ROS workspace

### ISSUE THREAD

**Issue by chukcha2** [robofit/but_velodyne#12]
Hello, I cloned but_velodyne, added it to a ROS workspace and tried to build it and got the following error:

```
CMake Error at but_velodyne/but_velodyne_odom/CMakeLists.txt:33 (find_package):
  By not providing "Findbut_velodyne.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "but_velodyne", but CMake did not find one.
```

I am not very familiar with cmake but is cmake saying that but_velodyne_odom requires but_velodyne. If so, isn't it a circular dependency (I am building but_velodyne).

**Comment by martin-velas** [comment]
Hello! Have you already built [but_velodyne_lib](https://github.com/martin-velas/but_velodyne_lib)? This library is required in order to build ROS package but_velodyne. I have just added this into into the readme (sry for missing info).

**Comment by rebellojason7** [comment]
Hi, I am experiencing the same error. I did install the but_velodyne_lib. with a sudo make install as the final step. However there isnt a package named but_velodyne. Should something be changed ?

**Comment by martin-velas** [comment]
Hi, try to set CMake property `but_velodyne_DIR` to `/usr/local/lib/cmake/but_velodyne-0.1`. Hope it helps, Martin.

**Comment by martin-velas** [comment]
Thanks for pointing this out! The link to but_velodyne_lib was fixed in my answer above.

I have not noticed this error - of course - my branch is quite under the construction ...

**Comment by ModiGit** [comment]
No problem, thanks for sharing these great libraries and for all the support!

**Comment by supersampard** [comment]
I don't know what's mean " Hi, try to set CMake property but_velodyne_DIR to /usr/local/lib/cmake/but_velodyne-0.1. Hope it helps, Martin. " Could you explain in detail?

**Comment by martin-velas** [comment]
Catkin project is actually CMake project. In order to build and link it properly, sometimes you need to specify the paths to libraries explicitly. Run this within the `build` directory of your catkin workspace:
```ivelas@ivelas-pc:~/catkin_ws/build$ ccmake ../src```
Find the line of property `but_velodyne_DIR` and set it to: /usr/local/lib/cmake/but_velodyne-0.1 (or whatever location you have used for installation of but_velodyne_lib)

![image](https://user-images.githubusercontent.com/5710925/29364199-fe8411ae-8292-11e7-99ed-75304376fe2e.png)

Hope it helps. Cheers!

**Comment by supersampard** [comment]
I followed your comment. However, it didn't work. 
![53](https://user-images.githubusercontent.com/23619435/29365513-49d76e0a-82d2-11e7-825c-397f7fdd89b8.PNG)
![54](https://user-images.githubusercontent.com/23619435/29365514-49e5ccc0-82d2-11e7-8d40-7b008bc5ea5b.PNG)

**Comment by martin-velas** [comment]
It seems that you did not installed `but_velodyne_lib` into `/home/saesaem/local/lib/cmake/but_velodyne-0.1`- this is necessary requirement as Readme says. Check, if this directory actually exists.

**Comment by supersampard** [comment]
my but_velodyne_lib is in here.
home/QuanergySystems/catkin_ws/src/but_velodyne_lib
So I retried and then the result was same....
![55](https://user-images.githubusercontent.com/23619435/29366042-dca6ef48-82d3-11e7-9b86-1c9a3299d926.PNG)
![56](https://user-images.githubusercontent.com/23619435/29366043-dca76662-82d3-11e7-9fc9-d17e516babcd.PNG)

**Comment by supersampard** [comment]
Thank you for help! I think I solved this one.
I found the location where but_velodyne-config.cmake is and set it to but_velodyne_DIR
Thank you so much!
![57](https://user-images.githubusercontent.com/23619435/29367224-26f3c0e6-82d7-11e7-8fe4-2c3cb1522a97.PNG)

**Comment by supersampard** [comment]
Could you explain this problem?
![62](https://user-images.githubusercontent.com/23619435/29392849-41fb22e4-833b-11e7-85ec-e84fb6212b22.PNG)
my CMakeLists.txt and package.xml are below
![60](https://user-images.githubusercontent.com/23619435/29392878-7354539c-833b-11e7-93a8-e686c417dcda.PNG)
![61](https://user-images.githubusercontent.com/23619435/29392879-7356787a-833b-11e7-923b-70e35e8c990e.PNG)

**Comment by supersampard** [comment]
I solved it Thank you so much!
I just modified like this
 #include <but_velodyne/VelodynePointCloud.h> -> #include <header file's location/VelodynePointCloud.h>

and then, I met a new problem.
I hope someone know this solution.
![63](https://user-images.githubusercontent.com/23619435/29396971-468f7920-8356-11e7-954f-690bde409590.PNG)

**Comment by martin-velas** [comment]
You should not set "header file's location" into `#include <...>`. The fact, that neither `but_velodyne/VelodynePointCloud.h` nor `-lbut_velodyne` can be found means, that the `but_velodyne_DIR` is not correctly set. I suggest:
 - set `CMAKE_INSTALL_PREFIX` property of `but_velodyne_lib` to `/home/saesaem/local`
 - run `make install`
 - than find `but_velodyne-config.cmake` file in somewhere in `/home/saesaem/local` and set `but_velodyne_DIR` to parent directory of this file

**Comment by supersampard** [comment]
Thank you martin-velas!

my step was :
1. mkdir -p ~/QuanergySystems/catkin_ws/src
2. cd ~/QuanergySystems/catkin_ws/src
3. catkin_init_workspace
4. git clone https://github.com/robofit/but_velodyne.git
5. cd ~/QuanergySystems/catkin_ws
6. catkin_make

7. issue
![68](https://user-images.githubusercontent.com/23619435/29443931-88d338d8-8416-11e7-93dc-38e2431aea1a.PNG)

8. cd build; ccmake ../src
![69](https://user-images.githubusercontent.com/23619435/29443969-cba628b4-8416-11e7-85a4-9bbb0fb2f99c.PNG)
press [c] to configure

9. issue
![70](https://user-images.githubusercontent.com/23619435/29443986-eb97b9bc-8416-11e7-98bb-8c17b338370d.PNG)

10. back to number 8th
change but_velodyne_DIR -> /home/saesaem/QuanergySystems/catkin_ws/src/but_velodyne_lib/bin
![71](https://user-images.githubusercontent.com/23619435/29444023-2aaf9854-8417-11e7-8e3a-fd9fa7479eba.PNG)

11. catkin_make

12. issue
![72](https://user-images.githubusercontent.com/23619435/29444092-cb0eb712-8417-11e7-9d29-0bccb9450927.PNG)

**Comment by martin-velas** [comment]
but_velodyne_lib is dependency of but_velodyne ROS package. You need to set CMAKE_INSTALL_PREFIX for but_velodyne_lib (not for but_velodyne). run "make install" and then set "~/local/blablabla..." to property "but_velodyne_DIR" of but_velodyne ROS package.

**Comment by 2amour** [comment]
Hi, @martin-velas I meet some errors when I use catkin_make.
 CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
  Could not find a package configuration file provided by
  "velodyne_pointcloud" with any of the following names:

    velodyne_pointcloudConfig.cmake
    velodyne_pointcloud-config.cmake

  Add the installation prefix of "velodyne_pointcloud" to CMAKE_PREFIX_PATH
  or set "velodyne_pointcloud_DIR" to a directory containing one of the above
  files.  If "velodyne_pointcloud" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  but_velodyne/but_calibration_camera_velodyne/CMakeLists.txt:5 (find_package)


-- Could not find the required component 'velodyne_pointcloud'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
  Could not find a package configuration file provided by
  "velodyne_pointcloud" with any of the following names:

    velodyne_pointcloudConfig.cmake
    velodyne_pointcloud-config.cmake

  Add the installation prefix of "velodyne_pointcloud" to CMAKE_PREFIX_PATH
  or set "velodyne_pointcloud_DIR" to a directory containing one of the above
  files.  If "velodyne_pointcloud" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  but_velodyne/but_calibration_camera_velodyne/CMakeLists.txt:5 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/xiao/catkin_but_velodyne/build/CMakeFiles/CMakeOutput.log".
See also "/home/xiao/catkin_but_velodyne/build/CMakeFiles/CMakeError.log".
Invoking "cmake" failed

And I use ccmake ../src within build, and could not find but_velodyne_DIR, what's the problem?

**Comment by junzhang2016** [comment]
> Hi, @martin-velas I meet some errors when I use catkin_make.
> CMake Warning at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:76 (find_package):
> Could not find a package configuration file provided by
> "velodyne_pointcloud" with any of the following names:
> 
> ```
> velodyne_pointcloudConfig.cmake
> velodyne_pointcloud-config.cmake
> ```
> 
> Add the installation prefix of "velodyne_pointcloud" to CMAKE_PREFIX_PATH
> or set "velodyne_pointcloud_DIR" to a directory containing one of the above
> files. If "velodyne_pointcloud" provides a separate development package or
> SDK, be sure it has been installed.
> Call Stack (most recent call first):
> but_velodyne/but_calibration_camera_velodyne/CMakeLists.txt:5 (find_package)
> 
> -- Could not find the required component 'velodyne_pointcloud'. The following CMake error indicates that you either need to install the package with the same name or change your environment so that it can be found.
> CMake Error at /opt/ros/kinetic/share/catkin/cmake/catkinConfig.cmake:83 (find_package):
> Could not find a package configuration file provided by
> "velodyne_pointcloud" with any of the following names:
> 
> ```
> velodyne_pointcloudConfig.cmake
> velodyne_pointcloud-config.cmake
> ```
> 
> Add the installation prefix of "velodyne_pointcloud" to CMAKE_PREFIX_PATH
> or set "velodyne_pointcloud_DIR" to a directory containing one of the above
> files. If "velodyne_pointcloud" provides a separate development package or
> SDK, be sure it has been installed.
> Call Stack (most recent call first):
> but_velodyne/but_calibration_camera_velodyne/CMakeLists.txt:5 (find_package)
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/xiao/catkin_but_velodyne/build/CMakeFiles/CMakeOutput.log".
> See also "/home/xiao/catkin_but_velodyne/build/CMakeFiles/CMakeError.log".
> Invoking "cmake" failed
> 
> And I use ccmake ../src within build, and could not find but_velodyne_DIR, what's the problem?




Hi, I got the same problem. The solution is to git clone this package [velodyne](https://github.com/ros-drivers/velodyne)  into your `catkin_ws/src`, then compile `catkin_make`.

Meanwhile, you may got the problem:
> home/jun/my_catkin_wses/calibration_ws/src/velodyne/velodyne_driver/include/velodyne_driver/input.h:58:18: fatal error: pcap.h: No such file or directory

Then, you should 
`cd catkin_ws/
rosdep install --from-paths src --ignore-src --rosdistro kinetic -y` 
(following [this](https://github.com/ros-drivers/velodyne/issues/54#issuecomment-124150377) )

Then, compile
`catkin_make`

**Comment by martin-velas** [comment]
Thanks for the answer :) - I assume this issue can be closed.
